# Generated by Django 5.1 on 2024-09-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
