# Generated by Django 5.1 on 2024-09-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_likes_alter_video_is_approved_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
